language: node_js
node_js:
  - "0.8"
# before_install: npm install -g grunt-cli
before_install:
  # - npm install -g npm
  - npm install -g npm@latest
# install: npm install
before_script:
  - grunt staging
